# Generated by Django 2.1.3 on 2019-01-22 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamestore', '0005_auto_20190122_0253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='category',
            field=models.CharField(max_length=15),
        ),
    ]
