# Generated by Django 2.1.3 on 2019-01-22 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamestore', '0007_game_age_restriction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='price',
            field=models.FloatField(),
        ),
    ]
