# Generated by Django 2.1.3 on 2019-01-22 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamestore', '0008_auto_20190122_1632'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='role',
        ),
        migrations.AlterField(
            model_name='game',
            name='age_restriction',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
