# Generated by Django 2.1.3 on 2019-01-22 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamestore', '0011_userprofile_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='category',
            field=models.CharField(choices=[('ACTION', 'Action'), ('ADVENTURE', 'Adventure'), ('ARCADE', 'Arcade'), ('FANTASY', 'Fantasy'), ('FIGHTING', 'Fighting'), ('PUZZLE', 'Puzzle'), ('SIMULATION', 'Simulation'), ('SPORTS', 'Sports'), ('STRATEGY', 'Strategy'), ('OTHER', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='game',
            name='description',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='game',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='bio',
            field=models.TextField(blank=True, max_length=200),
        ),
    ]
