# Generated by Django 2.1.3 on 2019-01-29 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gamestore', '0013_auto_20190122_2253'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='age',
        ),
    ]
