# Generated by Django 2.1.3 on 2019-02-09 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamestore', '0015_auto_20190203_1014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='category',
            field=models.CharField(choices=[('ACTION', 'Action'), ('ACTION-ADVENTURE', 'Action-adventure'), ('ADVENTURE', 'Adventure'), ('ARCADE', 'Arcade'), ('FANTASY', 'Fantasy'), ('FIGHTING', 'Fighting'), ('PUZZLE', 'Puzzle'), ('ROLE-PLAYING', 'Role-playing'), ('SIMULATION', 'Simulation'), ('SPORTS', 'Sports'), ('STRATEGY', 'Strategy'), ('OTHER', 'Other')], max_length=20),
        ),
    ]
