# Generated by Django 2.1.3 on 2019-02-09 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamestore', '0017_purchase_ref'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='ref',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
