# Generated by Django 2.1.3 on 2019-02-10 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gamestore', '0018_auto_20190209_1948'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='birthDate',
            new_name='birth_date',
        ),
    ]
