# Generated by Django 2.1.3 on 2019-02-10 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gamestore', '0019_auto_20190210_1554'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='gameUrl',
            new_name='game_url',
        ),
        migrations.RenameField(
            model_name='game',
            old_name='pictureUrl',
            new_name='picture_url',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='photoUrl',
            new_name='photo_url',
        ),
        migrations.RemoveField(
            model_name='gamestate',
            name='gameInState',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='purchasedGame',
        ),
        migrations.RemoveField(
            model_name='score',
            name='gameInScore',
        ),
        migrations.RemoveField(
            model_name='wishlist',
            name='potentialBuyer',
        ),
        migrations.RemoveField(
            model_name='wishlist',
            name='wishedGame',
        ),
        migrations.AddField(
            model_name='gamestate',
            name='game_in_state',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='game_in_state', to='gamestore.Game'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='purchase',
            name='purchased_game',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='purchased_game', to='gamestore.Game'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='score',
            name='game_in_score',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='game_in_score', to='gamestore.Game'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wishlist',
            name='potential_buyer',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='potential_buyer', to='gamestore.UserProfile'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wishlist',
            name='wished_game',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='wished_game', to='gamestore.Game'),
            preserve_default=False,
        ),
    ]
