# Generated by Django 2.1.5 on 2019-02-11 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamestore', '0020_auto_20190210_1621'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='complete',
            field=models.BooleanField(default=False),
        ),
    ]
