# Generated by Django 2.0.8 on 2019-02-20 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamestore', '0023_auto_20190219_0459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('D', 'Developer'), ('P', 'Player')], default='P', max_length=1),
        ),
    ]
