# Generated by Django 2.1.3 on 2019-01-07 19:47

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('price', models.PositiveIntegerField()),
                ('pictureUrl', models.URLField(blank=True)),
                ('description', models.TextField()),
                ('gameUrl', models.URLField()),
                ('date', models.DateField(default=datetime.date.today)),
            ],
            options={
                'ordering': ['-date', 'name'],
            },
        ),
        migrations.CreateModel(
            name='GameState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=50)),
                ('date', models.DateField(default=datetime.date.today)),
                ('gameInState', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gameInState', to='gamestore.Game')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.PositiveIntegerField()),
                ('date', models.DateField(default=datetime.date.today)),
                ('gameInScore', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gameInScore', to='gamestore.Game')),
            ],
            options={
                'ordering': ['-value'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birthYear', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=5)),
                ('country', models.CharField(max_length=15)),
                ('city', models.CharField(max_length=15)),
                ('address', models.CharField(max_length=15)),
                ('bio', models.TextField()),
                ('photoUrl', models.URLField(blank=True)),
                ('role', models.CharField(max_length=15)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WishList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('potentialBuyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='potentialBuyer', to='gamestore.User')),
                ('wishedGame', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishedGame', to='gamestore.Game')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.AddField(
            model_name='score',
            name='scorer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scorer', to='gamestore.User'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='buyer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buyer', to='gamestore.User'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='purchasedGame',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchasedGame', to='gamestore.Game'),
        ),
        migrations.AddField(
            model_name='gamestate',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player', to='gamestore.User'),
        ),
        migrations.AddField(
            model_name='game',
            name='developer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='developer', to='gamestore.User'),
        ),
    ]
