# Generated by Django 2.1.3 on 2019-01-08 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamestore', '0002_auto_20190108_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birthDate',
            field=models.DateField(blank=True),
        ),
    ]
