# Generated by Django 2.1.5 on 2019-02-03 10:14

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('gamestore', '0014_remove_userprofile_age'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'ordering': ['user_id']},
        ),
        migrations.AlterField(
            model_name='gamestate',
            name='state',
            field=jsonfield.fields.JSONField(),
        ),
    ]
