# Generated by Django 2.1.3 on 2019-02-09 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamestore', '0016_auto_20190209_1217'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='ref',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
    ]
