# Generated by Django 2.1.3 on 2019-02-14 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamestore', '0021_purchase_complete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='description',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
